### ISSUE TITLE
Problems with building...

### ISSUE THREAD

**Issue by johnshields** [johhnry/static-site-rs#1]
Maybe it is because I am new to rust, but I am having problems trying to build this, any help would be appreciated!

![Screenshot 2023-06-20 002722](https://github.com/johhnry/static-site-rs/assets/26766163/dd27315e-f975-4b50-b90d-bae75237c692)

**Comment by johhnry** [comment]
Hi @johnshields,

You can run the executable by either:

- `cargo run ...` which will build and run the executable right away. So you can do `cargo run build` (which is equivalent to `static-site-rs build`) but be careful that it will try to build the website in the current working directory (so the git repo)

- `cargo build` then launch it from the `target` directory where the files are built: `./target/debug/static-site-rs build` (in debug mode, `./target/release/static-site-rs` when using `cargo build --release`)

But you need to run the command in your website's project directory so I would suggest adding the build folder to your PATH or make an alias

Note: this project is very simple and was made for personal purposes ;)
